### ISSUE TITLE
Missing the "ChangeTransitionMixRate" option for the "Auto" function.

### ISSUE THREAD

**Issue by Marc-Girard** [camikura/go-atem#2]
Hi there!

First, thanks for your cool ATEM Go Module/Library.    Just wanted to point out that the "ChangeTransitionMixRate" option is missing from your implementation and that it can simply be added using those three lines (around line #446):

```
func (d *Device) ChangeTransitionMixRate(me int, rate int) {
	d.SendCommand("CTMx", []byte{byte(me), byte(rate), 0, 0})
}

```
So now we can set the rate for auto transitions.    INT (rate) must be between 1-250.

Cheers!

**Comment by camikura** [comment]
@Marc-Girard Thank you!
